<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

use Validator;
use Auth;

use Hash; //验证密码


class AdminPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return Auth::guard('admin')->check();
    }

    /**
     *
     * 使用扩展验证
     */
    public function addvalidator()
    {
        // 验证用户的原来密码
        Validator::extend('check_password', function ($attribute, $value, $parameters, $validator) {
            //  这里的value  就是表单输入项
            return Hash::check($value, Auth::guard('admin')->user()->password);
        });
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $this->addvalidator();
        return [
            'oldpassword'           => 'sometimes|required|check_password',
            'password'              => 'sometimes|required|confirmed',
            'password_confirmation' => 'sometimes|required',
        ];
    }

    /**
     * 中文提示信息
     * @return array
     */
    public function messages()
    {
        return [
            'oldpassword.required'           => '原来的密码不能为空!',
            'oldpassword.check_password'     => '原来的密码不正确',
            'password.required'              => '新密码不能为空!',
            'password.confirmed'             => '两次密码不一致',
            'password_confirmation.required' => '确认密码不能为空!',
        ]; // TODO: Change the autogenerated stub
    }
}